#!/usr/bin/env python3
"""Generate deterministic ACE-2 RMSNorm RTL vectors from the Python reference."""

from __future__ import annotations

import hashlib
import json
import math
import random
import struct
from pathlib import Path

from ace2_rmsnorm_reference import (
    BEATS,
    HIDDEN_SIZE,
    derive_rmsnorm_output_scale,
    derive_scaled_gains_q8,
    pack_gain_beats,
    pack_int8_beats,
    reference_rmsnorm,
    rmsnorm_gain_scale_floor,
)


ROOT = Path(__file__).resolve().parents[1]
OUT_SVH = ROOT / "verification" / "generated" / "rmsnorm_vectors.svh"
OUT_JSON = ROOT / "verification" / "generated" / "rmsnorm_vectors.json"


def _pattern_cases() -> list[tuple[str, list[int], list[float], float]]:
    unity_weight = [1.0] * HIDDEN_SIZE
    cases: list[tuple[str, list[int], list[float], float]] = [
        ("all_zero", [0] * HIDDEN_SIZE, unity_weight, 1.0 / 32.0),
        ("all_one", [1] * HIDDEN_SIZE, unity_weight, 3.0 / 128.0),
        (
            "alternating_extremes",
            [127 if index % 2 else -128 for index in range(HIDDEN_SIZE)],
            unity_weight,
            1.0 / 64.0,
        ),
        (
            "ramp",
            [((index * 17 + 11) % 256) - 128 for index in range(HIDDEN_SIZE)],
            [0.875 + (index % 17) / 64.0 for index in range(HIDDEN_SIZE)],
            5.0 / 128.0,
        ),
        (
            "half_lsb_ties",
            [1] * HIDDEN_SIZE,
            [
                (128 if index % 4 < 2 else 384) * (1.0 / 16.0) / 256.0
                for index in range(HIDDEN_SIZE)
            ],
            1.0 / 16.0,
        ),
        (
            "sparse_signed_saturation",
            [127, -128] + [0] * (HIDDEN_SIZE - 2),
            [32767.0 / 32768.0] * HIDDEN_SIZE,
            1.0 / 128.0,
        ),
    ]

    rng = random.Random(0xACE20001)
    random_scales = [1.0 / 64.0, 3.0 / 128.0, 1.0 / 32.0, 5.0 / 128.0]
    for case_index in range(8):
        activations = [rng.randint(-128, 127) for _ in range(HIDDEN_SIZE)]
        weights = [rng.uniform(0.75, 1.25) for _ in range(HIDDEN_SIZE)]
        cases.append(
            (
                f"seeded_random_{case_index}",
                activations,
                weights,
                random_scales[case_index % len(random_scales)],
            )
        )
    floor_weights = [1.25 if index == 0 else 0.875 for index in range(HIDDEN_SIZE)]
    floor_absmax = 0.25
    cases.append(
        (
            "gain_scale_floor_dominates",
            [((index * 11 + 5) % 31) - 15 for index in range(HIDDEN_SIZE)],
            floor_weights,
            derive_rmsnorm_output_scale(floor_weights, floor_absmax),
        )
    )
    return cases


def _hex(value: int, width_bits: int) -> str:
    return f"{width_bits}'h{value & ((1 << width_bits) - 1):0{width_bits // 4}x}"


def main() -> None:
    OUT_SVH.parent.mkdir(parents=True, exist_ok=True)
    records = []
    sv_lines = [
        "// Generated by tools/gen_rmsnorm_vectors.py; do not edit by hand.",
        f"localparam integer TEST_COUNT = {len(_pattern_cases())};",
        f"localparam integer TEST_BEATS = {BEATS};",
        "reg [8*16-1:0] test_input_beats [0:TEST_COUNT*TEST_BEATS-1];",
        "reg [16*16-1:0] test_gain_beats [0:TEST_COUNT*TEST_BEATS-1];",
        "reg [8*16-1:0] test_expected_beats [0:TEST_COUNT*TEST_BEATS-1];",
        "reg [48-1:0] test_expected_sumsq [0:TEST_COUNT-1];",
        "reg [32-1:0] test_expected_inv [0:TEST_COUNT-1];",
        "reg test_expected_saturation [0:TEST_COUNT-1];",
        "initial begin",
    ]

    for case_index, (name, activations, weights, output_scale) in enumerate(_pattern_cases()):
        calibrated_output_absmax = (
            0.25 if name == "gain_scale_floor_dominates" else output_scale * 127.0
        )
        calibrated_absmax_scale = calibrated_output_absmax / 127.0
        gain_scale_floor = rmsnorm_gain_scale_floor(weights)
        derived_output_scale = derive_rmsnorm_output_scale(
            weights,
            calibrated_output_absmax,
        )
        if not math.isclose(output_scale, derived_output_scale, rel_tol=0.0, abs_tol=1e-15):
            raise AssertionError(
                f"{name}: output scale {output_scale} != derived {derived_output_scale}"
            )
        scale_source = (
            "gain_representability_floor"
            if gain_scale_floor > calibrated_absmax_scale
            else "calibrated_bf16_output_absmax"
        )
        gains = derive_scaled_gains_q8(weights, output_scale)
        result = reference_rmsnorm(activations, gains)
        input_beats = pack_int8_beats(activations)
        gain_beats = pack_gain_beats(gains)
        expected_beats = pack_int8_beats(result.outputs)
        records.append(
            {
                "name": name,
                "calibrated_bf16_output_absmax": calibrated_output_absmax,
                "calibrated_bf16_output_absmax_divided_by_127": calibrated_absmax_scale,
                "gain_representability_scale_floor": gain_scale_floor,
                "output_scale": output_scale,
                "output_scale_source": scale_source,
                "sumsq": result.sumsq,
                "inv_rms_q30": result.inv_rms_q30,
                "saturation_seen": result.saturation_seen,
                "input_sha256": hashlib.sha256(bytes((value & 0xFF) for value in activations)).hexdigest(),
                "weight_sha256": hashlib.sha256(
                    b"".join(struct.pack("<d", value) for value in weights)
                ).hexdigest(),
                "gain_sha256": hashlib.sha256(
                    b"".join(int(value & 0xFFFF).to_bytes(2, "little") for value in gains)
                ).hexdigest(),
                "output_sha256": hashlib.sha256(bytes((value & 0xFF) for value in result.outputs)).hexdigest(),
            }
        )
        sv_lines.append(f"  // case {case_index}: {name}")
        sv_lines.append(f"  test_expected_sumsq[{case_index}] = {_hex(result.sumsq, 48)};")
        sv_lines.append(f"  test_expected_inv[{case_index}] = {_hex(result.inv_rms_q30, 32)};")
        sv_lines.append(f"  test_expected_saturation[{case_index}] = 1'b{1 if result.saturation_seen else 0};")
        for beat_index in range(BEATS):
            flat_index = case_index * BEATS + beat_index
            sv_lines.append(f"  test_input_beats[{flat_index}] = {_hex(input_beats[beat_index], 128)};")
            sv_lines.append(f"  test_gain_beats[{flat_index}] = {_hex(gain_beats[beat_index], 256)};")
            sv_lines.append(f"  test_expected_beats[{flat_index}] = {_hex(expected_beats[beat_index], 128)};")

    sv_lines.append("end")
    OUT_SVH.write_text("\n".join(sv_lines) + "\n", encoding="utf-8")
    OUT_JSON.write_text(
        json.dumps(
            {
                "schema_version": 3,
                "generator": "tools/gen_rmsnorm_vectors.py",
                "reference": "tools/ace2_rmsnorm_reference.py",
                "hidden_size": HIDDEN_SIZE,
                "beats": BEATS,
                "output_format": {
                    "storage": "signed_int8",
                    "scale": "static_per_test_tensor",
                    "scale_derivation": "maximum_of_calibrated_BF16_output_absmax_divided_by_127_and_maximum_absolute_gain_times_2^8_divided_by_32767",
                    "gain_metadata": "signed_int16_Q7.8_of_weight_divided_by_output_scale",
                    "rounding": "nearest_ties_to_even",
                    "saturation": [-128, 127],
                },
                "cases": records,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
